# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainViewUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(997, 518)
        MainWindow.setTabletTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgRc/images/analytics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setAutoFillBackground(False)
        self.mdiArea.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.mdiArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mdiArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mdiArea.setLineWidth(1)
        self.mdiArea.setMidLineWidth(0)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setActivationOrder(QtWidgets.QMdiArea.CreationOrder)
        self.mdiArea.setViewMode(QtWidgets.QMdiArea.SubWindowView)
        self.mdiArea.setDocumentMode(False)
        self.mdiArea.setTabsClosable(True)
        self.mdiArea.setTabsMovable(True)
        self.mdiArea.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidgetDataView = QtWidgets.QDockWidget(MainWindow)
        self.dockWidgetDataView.setMinimumSize(QtCore.QSize(162, 264))
        self.dockWidgetDataView.setAccessibleName("")
        self.dockWidgetDataView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidgetDataView.setAutoFillBackground(False)
        self.dockWidgetDataView.setFloating(False)
        self.dockWidgetDataView.setObjectName("dockWidgetDataView")
        self.dockWidgetContentsDataSet = QtWidgets.QWidget()
        self.dockWidgetContentsDataSet.setObjectName("dockWidgetContentsDataSet")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContentsDataSet)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBoxFileData = QtWidgets.QGroupBox(self.dockWidgetContentsDataSet)
        self.groupBoxFileData.setObjectName("groupBoxFileData")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxFileData)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textBrowserFileData = QtWidgets.QTextBrowser(self.groupBoxFileData)
        self.textBrowserFileData.setObjectName("textBrowserFileData")
        self.gridLayout_5.addWidget(self.textBrowserFileData, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxFileData, 1, 0, 1, 1)
        self.groupBoxAccessibleData = QtWidgets.QGroupBox(self.dockWidgetContentsDataSet)
        self.groupBoxAccessibleData.setObjectName("groupBoxAccessibleData")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBoxAccessibleData)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.listViewAccessibleData = QtWidgets.QListView(self.groupBoxAccessibleData)
        self.listViewAccessibleData.setObjectName("listViewAccessibleData")
        self.gridLayout_6.addWidget(self.listViewAccessibleData, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxAccessibleData, 0, 0, 1, 1)
        self.dockWidgetDataView.setWidget(self.dockWidgetContentsDataSet)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetDataView)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNelp = QtWidgets.QMenu(self.menubar)
        self.menuNelp.setObjectName("menuNelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuMore = QtWidgets.QMenu(self.menuView)
        self.menuMore.setObjectName("menuMore")
        self.menuAnalysisTools = QtWidgets.QMenu(self.menubar)
        self.menuAnalysisTools.setObjectName("menuAnalysisTools")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidgetProtocol = QtWidgets.QDockWidget(MainWindow)
        self.dockWidgetProtocol.setTabletTracking(False)
        self.dockWidgetProtocol.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dockWidgetProtocol.setFloating(False)
        self.dockWidgetProtocol.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidgetProtocol.setObjectName("dockWidgetProtocol")
        self.dockWidgetContentsProtocol = QtWidgets.QWidget()
        self.dockWidgetContentsProtocol.setObjectName("dockWidgetContentsProtocol")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContentsProtocol)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBoxProtocolDetails = QtWidgets.QGroupBox(self.dockWidgetContentsProtocol)
        self.groupBoxProtocolDetails.setObjectName("groupBoxProtocolDetails")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxProtocolDetails)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBrowserProtocolDetails = QtWidgets.QTextBrowser(self.groupBoxProtocolDetails)
        self.textBrowserProtocolDetails.setObjectName("textBrowserProtocolDetails")
        self.gridLayout_3.addWidget(self.textBrowserProtocolDetails, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxProtocolDetails, 1, 0, 1, 1)
        self.treeViewProtocol = QtWidgets.QTreeView(self.dockWidgetContentsProtocol)
        self.treeViewProtocol.setObjectName("treeViewProtocol")
        self.gridLayout_2.addWidget(self.treeViewProtocol, 0, 0, 1, 1)
        self.dockWidgetProtocol.setWidget(self.dockWidgetContentsProtocol)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidgetProtocol)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBarActions = QtWidgets.QToolBar(MainWindow)
        self.toolBarActions.setObjectName("toolBarActions")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarActions)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgRc/images/inbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionDataAnalysisHelp = QtWidgets.QAction(MainWindow)
        self.actionDataAnalysisHelp.setObjectName("actionDataAnalysisHelp")
        self.actionAboutUI = QtWidgets.QAction(MainWindow)
        self.actionAboutUI.setObjectName("actionAboutUI")
        self.actionUsage = QtWidgets.QAction(MainWindow)
        self.actionUsage.setObjectName("actionUsage")
        self.actionSaveAll = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/imgRc/images/outbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAll.setIcon(icon2)
        self.actionSaveAll.setObjectName("actionSaveAll")
        self.actionDataView = QtWidgets.QAction(MainWindow)
        self.actionDataView.setCheckable(True)
        self.actionDataView.setChecked(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/imgRc/images/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDataView.setIcon(icon3)
        self.actionDataView.setObjectName("actionDataView")
        self.actionProtocolRender = QtWidgets.QAction(MainWindow)
        self.actionProtocolRender.setCheckable(True)
        self.actionProtocolRender.setChecked(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/imgRc/images/analytics-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProtocolRender.setIcon(icon4)
        self.actionProtocolRender.setObjectName("actionProtocolRender")
        self.actionShowFileData = QtWidgets.QAction(MainWindow)
        self.actionShowFileData.setCheckable(True)
        self.actionShowFileData.setChecked(True)
        self.actionShowFileData.setObjectName("actionShowFileData")
        self.actionShowAdditionalDetails = QtWidgets.QAction(MainWindow)
        self.actionShowAdditionalDetails.setCheckable(True)
        self.actionShowAdditionalDetails.setChecked(True)
        self.actionShowAdditionalDetails.setObjectName("actionShowAdditionalDetails")
        self.actionCloseAll = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/imgRc/images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCloseAll.setIcon(icon5)
        self.actionCloseAll.setObjectName("actionCloseAll")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAll)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuNelp.addAction(self.actionDataAnalysisHelp)
        self.menuNelp.addSeparator()
        self.menuNelp.addAction(self.actionUsage)
        self.menuMore.addAction(self.actionShowFileData)
        self.menuMore.addAction(self.actionShowAdditionalDetails)
        self.menuView.addAction(self.actionDataView)
        self.menuView.addAction(self.actionProtocolRender)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuMore.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionCloseAll)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAnalysisTools.menuAction())
        self.menubar.addAction(self.menuNelp.menuAction())
        self.toolBar.addAction(self.actionDataView)
        self.toolBar.addAction(self.actionProtocolRender)
        self.toolBar_2.addAction(self.actionCloseAll)
        self.toolBarActions.addAction(self.actionOpen)
        self.toolBarActions.addAction(self.actionSaveAll)

        self.retranslateUi(MainWindow)
        self.actionDataView.toggled['bool'].connect(self.dockWidgetDataView.setVisible)
        self.actionProtocolRender.toggled['bool'].connect(self.dockWidgetProtocol.setVisible)
        self.dockWidgetProtocol.visibilityChanged['bool'].connect(self.actionProtocolRender.setChecked)
        self.dockWidgetDataView.visibilityChanged['bool'].connect(self.actionDataView.setChecked)
        self.actionShowAdditionalDetails.toggled['bool'].connect(self.groupBoxProtocolDetails.setVisible)
        self.actionShowFileData.toggled['bool'].connect(self.groupBoxFileData.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data analysis"))
        self.dockWidgetDataView.setWindowTitle(_translate("MainWindow", "Data view"))
        self.groupBoxFileData.setTitle(_translate("MainWindow", "File data"))
        self.groupBoxAccessibleData.setTitle(_translate("MainWindow", "Accessible data"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuNelp.setTitle(_translate("MainWindow", "&Help"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuMore.setTitle(_translate("MainWindow", "More..."))
        self.menuAnalysisTools.setTitle(_translate("MainWindow", "&Analysis tools"))
        self.dockWidgetProtocol.setWindowTitle(_translate("MainWindow", "Protocol"))
        self.groupBoxProtocolDetails.setTitle(_translate("MainWindow", "Additional details"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBarActions.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "&Open..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "&Save selected"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save selected"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionDataAnalysisHelp.setText(_translate("MainWindow", "&About"))
        self.actionAboutUI.setText(_translate("MainWindow", "About UI"))
        self.actionUsage.setText(_translate("MainWindow", "Usage"))
        self.actionUsage.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionSaveAll.setText(_translate("MainWindow", "&Save all"))
        self.actionDataView.setText(_translate("MainWindow", "Data view"))
        self.actionDataView.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionProtocolRender.setText(_translate("MainWindow", "Protocol render"))
        self.actionProtocolRender.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionShowFileData.setText(_translate("MainWindow", "Show file data"))
        self.actionShowAdditionalDetails.setText(_translate("MainWindow", "Show additional details"))
        self.actionCloseAll.setText(_translate("MainWindow", "Close all"))

import dataAnalysisRC
